apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apptv-ingress
  namespace: web-comedor-apptv
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: apptv.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apptv-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: apptv-backend-service
            port:
              number: 3000 