apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apptv-ingress
  namespace: web-comedor-apptv
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - apptvcomedor.unicen.edu.ar
    secretName: apptvcomedor-tls
  rules:
  - host: apptvcomedor.unicen.edu.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apptv-frontend-service
            port:
              number: 80

