apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apptv-backend-secrets
  namespace: web-comedor-apptv
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: apptv-backend-env
    type: Secret
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/apptv-backend
        property: JWT_SECRET
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: secret/data/apptv-backend
        property: ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: secret/data/apptv-backend
        property: ADMIN_PASSWORD 