apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor.unicen.edu.ar
spec:
  type: kv-v2
  mount: kubernetes
  path: web/HARBOR_AUTH
  destination:
    name: harbor.unicen.edu.ar
    create: true
    type: kubernetes.io/dockerconfigjson
  refreshAfter: 300s
  vaultAuthRef: static-auth