apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apptv-database-pvc
  namespace: web-comedor-apptv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apptv-uploads-pvc
  namespace: web-comedor-apptv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 